import { type EmailOtpType } from '@supabase/supabase-js'
import { type NextRequest, NextResponse } from 'next/server'
import { postAuthRedirectResponse } from '@/lib/auth/post-auth-redirect'
import { createSupabaseServerClient } from '@/lib/supabase/server'

// Auth callback. Two link formats supported:
//   * ?code=...                   (PKCE — Google OAuth + newer email templates)
//   * ?token_hash=...&type=...    (magic link / email OTP — legacy email links)
//
// Email-confirmation links generated by /signup and /verify now point at
// /auth/confirm instead, which is more lenient about a missing `type`
// param (some email clients strip it). /auth/callback stays for OAuth and
// for backwards-compatibility with email links already in flight.
//
// Supabase may also bounce back with ?error=...&error_description=... when
// it rejects the link before it ever hits us (most often: the redirect URL
// isn't on the allow-list, or the link expired).
//
// On success → redirect to the next destination (default /).
// On any failure → redirect to /login with the actual error surfaced as a
// query param so the user sees what's wrong.
export async function GET(request: NextRequest) {
  const { searchParams, origin } = request.nextUrl
  const code = searchParams.get('code')
  const tokenHash = searchParams.get('token_hash')
  const type = searchParams.get('type') as EmailOtpType | null
  const next = searchParams.get('next') ?? '/'

  // Supabase rejected the link upstream and bounced back with error info.
  const upstreamError = searchParams.get('error_description')
  if (upstreamError) {
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(upstreamError)}`, origin),
    )
  }

  const supabase = await createSupabaseServerClient()

  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    if (!error) {
      return await postAuthRedirectResponse(request, supabase, origin, next)
    }
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(error.message)}`, origin),
    )
  }

  if (tokenHash && type) {
    const { error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type,
    })
    if (!error) {
      return await postAuthRedirectResponse(request, supabase, origin, next)
    }
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(error.message)}`, origin),
    )
  }

  // Bare token_hash with no type: same lenient fallback as /auth/confirm,
  // since some email clients strip the &type=… portion of the URL.
  if (tokenHash) {
    const { error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: 'signup' as EmailOtpType,
    })
    if (!error) {
      return await postAuthRedirectResponse(request, supabase, origin, next)
    }
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(error.message)}`, origin),
    )
  }

  return NextResponse.redirect(
    new URL('/login?error=Missing+verification+token', origin),
  )
}
